Skip counter culture update
magnusvk/counter_culture pull request #371
Opened 2023-06-27 15:15 UTC by RuslanHassonov

Added the option to wrap code in `Model.skip_counter_culture_updates { ... }` block. With this block, we are able to skip counter_culture create, update and destroy callbacks when required and prevent unnecessary database queries.

2023-06-27 20:32 UTC, magnusvk commented
Could you just skip all callbacks instead? That strikes me as possibly the simpler solution here...

2023-06-28 07:14 UTC, RuslanHassonov commented
@benjaminwols can you please review this?

2023-06-28 07:15 UTC, benjaminwols requested changes

2023-06-28 07:15 UTC, benjaminwols commented on lib/counter_culture/extensions.rb
> +        counter_culture_updates_was = Thread.current[:skip_counter_culture_updates]
Something like this
```suggestion
        return unless block_given?

        counter_culture_updates_was = Thread.current[:skip_counter_culture_updates]
```

2023-06-28 07:19 UTC, RuslanHassonov commented
> Could you just skip all callbacks instead? That strikes me as possibly the simpler solution here...

@magnusvk I'm not entirely sure what you mean. Could you please make a suggestion?

2023-06-28 21:35 UTC, magnusvk commented
counter_culture uses ActiveRecord callbacks. So if you save / insert your records in a way that doesn't trigger callbacks (for example `insert_all` or `update_columns`) then counter_culture won't be triggered. And, generally speaking, if your updates are performance-sensitive then that's probably what you want to do. So I'm inclined to say it's not worth introducing this complexity in the gem.

2023-06-29 13:26 UTC, RuslanHassonov commented
The reason why I've developed this change is because I still want to run validations and some callbacks of our own, but not counter_culture callbacks (not until later, at least). `.insert_all` or `.update_columns` will skip everything, which I'm trying to avoid.

2023-07-01 00:55 UTC, magnusvk reviewed
Fair enough. I'm frankly pretty reluctant to include this since it has never come up before, but it's simple enough that it's probably fine.

Can you also add some documentation for this in the readme file? Thanks.

2023-07-01 00:55 UTC, magnusvk commented on spec/counter_culture_spec.rb
> +    end
Can you add some code below that makes sure the updates resume at the end of the block?

2023-07-01 00:55 UTC, magnusvk commented on spec/counter_culture_spec.rb
> +    Review.skip_counter_culture_updates do
Same here

2023-07-01 00:55 UTC, magnusvk commented on spec/counter_culture_spec.rb
> +      user.reviews.last.destroy
And here

2023-07-01 00:55 UTC, magnusvk commented on spec/counter_culture_spec.rb
> +  end
Can you also add a separate set of tests that makes sure this behavior works correctly when using nested calls to `skip_counter_culture_updates` across multiple models?

2023-07-06 09:25 UTC, RuslanHassonov commented
@magnusvk Apologies for the late reply, I'll apply the suggested changes as soon as I'm able to.

2023-07-13 02:58 UTC, magnusvk approved these changes
Thank you!

2023-07-13 03:03 UTC, merged

2023-07-13 03:31 UTC, magnusvk commented
Released as gem version 3.4.0

2023-07-13 13:54 UTC, PhilCoggins commented
> Fair enough. I'm frankly pretty reluctant to include this since it has never come up before, but it's simple enough that it's probably fine.

*https://github.com/magnusvk/counter_culture/issues/299 has entered the chat*